version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-random-users
    container_name: laravel-random-users
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel-random-users-mysql
    environment:
      MYSQL_DATABASE: random_user
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
